### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by Azmodan95** [essserrr/slider#13]
https://github.com/essserrr/slider/blob/a4b5f466e7e23c83104717faad77305594f22844/src/slider/components/ObservableSubject/ObservableSubject.ts#L7
Для типизации типа функции лучше использовать синтаксис стрелочной функции к примеру `(value: number) => number`, так  в данном случае не понятно какого рода функцию нужно передавать.

---

https://github.com/essserrr/slider/blob/a4b5f466e7e23c83104717faad77305594f22844/src/slider/components/ObservableSubject/ObservableSubject.ts#L33
Для типизации объекта крайне нежелательно использовать `Object` так как этот тип совместим практически со всем даже с примитивами. Для типизации объекта будет более надежным литеральный тип `{ name: string }`, но это если известны свойства. Так как если использовать пустые фигурные скобки `{}` эквивалентно `object`, этот тип будет совместим с массивами и функциями. А вот если свойства объекта неизвестны то лучше всего использовать Record<string, unknown>, так как в этом случае мы сможем передать только объект и нечего другого.

---

https://github.com/essserrr/slider/blob/a4b5f466e7e23c83104717faad77305594f22844/src/slider/components/Controller/Controller.ts#L33
Нежелательно использовать постфикс `!` для того указать что значение точно будет, так подобное может привести к ошибкам. Лучше либо проверить явно что значение существует либо использовать оператор `?` к примеру `this.view.progressBar?.node`.

**Comment by essserrr** [comment]
Пофикшено

**Comment by Azmodan95** [comment]
https://github.com/essserrr/slider/blob/ecf40749c300d7d139601fa533b02a532ea61bd2/src/slider/components/View/SubViews/Handle/Handle.ts#L7
Тут еще нужно пересмотреть использование постфикса `!` в свойствах класса, так как в данном случае свойство все таки является не обязательным, так как назначается от условия. И соответственно при использовании постфикса `!`, typescript этого не видит, и его можно без каких либо проблем использовать, что опять же может привести к ошибкам.

---

https://github.com/essserrr/slider/blob/ecf40749c300d7d139601fa533b02a532ea61bd2/src/slider/components/View/SubViews/Handle/Handle.ts#L9
Для типизации примитивных типов нужно использовать соответствующие типы которые с маленькой буквы. Так как типы с большой буквы нужны для типизации значений созданных с использованием соответствующего конструктора, в данном случае это `new Boolean()`.

**Comment by Azmodan95** [comment]
https://github.com/essserrr/slider/blob/ecf40749c300d7d139601fa533b02a532ea61bd2/src/slider/components/ObservableSubject/ObservableSubject.ts#L22
И еще тут пропустил
