### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Azmodan95** [essserrr/slider#14]
Нужно отменить событие по умолчанию при перемещении бегунка, так как при зажатии левой кнопки мыши и ее перемещении срабатывает стандартное событие drag and drop, это правда не всегда проявляется, тем не менее когда проявляется перемещение бегунка, ломается.

---

Значения на шкале не соответствуют указанному шагу
https://user-images.githubusercontent.com/51163508/118971019-952e0500-b977-11eb-90e2-cd6a88101917.mp4

---

При клике на шкале бегунок периодически застревает не хочет перемещаться, так же еще бывает что он перемещается не на то значение по которому мы кликнули.
https://user-images.githubusercontent.com/51163508/118972087-d541b780-b978-11eb-9be3-a0749c9eedb1.mp4
https://user-images.githubusercontent.com/51163508/118971659-5cdaf680-b978-11eb-9ba8-ed57ceb366ea.mp4

**Comment by essserrr** [comment]
Пофикшено
